# Use new trusty images, should yield newer compilers and packages
sudo: required
dist: precise
language: cpp

notifications: 
  email: false

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
          packages:
            - g++-4.9
            - cmake
            - cmake-data
      env: COMPILER=g++-4.9
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
          packages:
            - g++-5
            - cmake
            - cmake-data
      env: COMPILER=g++-5
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
            - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
          packages:
            - clang-3.6
            - cmake
            - cmake-data
      env: COMPILER=clang++-3.6
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
            - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
          packages:
            - clang-3.7
            - cmake
            - cmake-data
      env: COMPILER=clang++-3.7

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libopencv-dev
script:
  - mkdir build 
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER .. 
  - make 
  - ctest -VV
  
